#!/usr/bin/env python3
"""Generate livox_camera_calib (ROS1) configs, one pair per virtual view.

RUN THIS ON THE ROS1 MACHINE, from inside this bundle. livox_camera_calib reads
absolute paths out of its YAML, so the configs must be generated where they will be
used -- generating them on the Pi would bake in Pi paths.

livox_camera_calib calibrates ONE image against ONE cloud per run, and splits its
settings across two files:

    calib_NN.yaml     ROS1 rosparam: common/camera/calib sections
    config_NN.yaml    OpenCV FileStorage: ExtrinsicMat (initial guess) + tuning

Each virtual view looks in a different direction, so each has its OWN initial
extrinsic. They are not interchangeable, and they must NOT be merged into a single
multi_calib run -- that solves for one shared extrinsic across all its inputs, which
is only valid for several scenes seen from the SAME camera pose.

Typical use on the ROS1 machine:

    cd <this bundle>
    python3 calib_make_configs.py --calib-repo ~/catkin_ws/src/livox_camera_calib
    bash configs/run_all.sh

Then bring configs/results/ back and run calib_prepare_views.py compose.
"""

import argparse
import os
import re
import stat
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Used when --calib-repo is not given. Mirrors livox_camera_calib's config_outdoor.yaml;
# prefer copying the real one from your clone so tuning matches your version.
FALLBACK_SCENE_CFG = """%YAML:1.0

# Topic names (only used when reading from a rosbag; ignored for image_file/pcd_file).
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

Data.custom_msg: 0

# Initial extrinsic -- REPLACED PER VIEW by calib_make_configs.py.
ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0, -1.0, 0.0, 0.0,
         0.0, 0.0, -1.0, 0.0,
         1.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 1.0]

# Params for Canny Edge Extraction
Canny.gray_threshold: 20
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 2.0
Voxel.down_sample_size: 0.02
Plane.min_points_size: 30
Plane.normal_theta_min: 30
Plane.normal_theta_max: 150
Plane.max_size: 5
Ransac.dis_threshold: 0.02
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06

# Params for color point clouds
Color.dense: 1
Color.intensity_threshold: 10
"""

# ROS1 rosparam layout: flat common/camera/calib sections (NOT the ROS2
# "<node>: ros__parameters:" nesting).
CALIB_TEMPLATE = """# Auto-generated by calib_make_configs.py -- view {idx:02d}, yaw {yaw:+.2f} deg.
# This view's initial extrinsic lives in:
#   {scene_cfg}
common:
    image_file: "{image_file}"
    pcd_file: "{pcd_file}"
    result_file: "{result_file}"

# EXACT intrinsics of the synthesized rectilinear view. A gnomonic cut out of an
# equirectangular panorama is a perfect pinhole image, so there is no lens distortion
# to model and these never need calibrating.
camera:
    camera_matrix: [{fx:.9f}, 0.0, {cx:.9f},
                    0.0, {fy:.9f}, {cy:.9f},
                    0.0, 0.0, 1.0]
    dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]

calib:
    calib_config_file: "{scene_cfg}"
    use_rough_calib: {rough}
"""

# Runs the node with an explicit config, so the cloned repo is never modified.
LAUNCH_TEMPLATE = """<launch>
  <!-- Auto-generated. Lets one config be chosen per run, leaving the cloned
       livox_camera_calib repo untouched (its own calib.launch hardcodes
       config/calib.yaml). Run by path:
         roslaunch {launch_path} config:=<...>/calib_00.yaml -->
  <arg name="config" />
    <!-- Load to global scope for binaries using NodeHandle() param lookup. -->
    <rosparam command="load" file="$(arg config)" />
  <node pkg="{pkg}" type="{exe}" name="lidar_camera_calib" output="screen">
        <!-- Also load to private scope for binaries using private (~) lookup. -->
    <rosparam command="load" file="$(arg config)" />
  </node>
</launch>
"""


def find_calib_repo(explicit):
    """Locate the livox_camera_calib source tree.

    Tries, in order: what the user passed, `rospack find`, then a few conventional
    catkin locations. Returns None if it cannot be found -- the generator still works,
    it just falls back to built-in tuning defaults.
    """
    import shutil
    import subprocess

    if explicit:
        path = os.path.abspath(os.path.expanduser(explicit))
        if not os.path.isdir(path):
            raise SystemExit(f"--calib-repo does not exist: {path}")
        return path

    if shutil.which("rospack"):
        try:
            out = subprocess.run(["rospack", "find", "livox_camera_calib"],
                                 capture_output=True, text=True, timeout=15)
            cand = out.stdout.strip()
            # rospack may resolve to an install space with no src/; only take it if
            # the source we need to read is actually there.
            if cand and os.path.isdir(os.path.join(cand, "config")):
                return cand
        except (subprocess.SubprocessError, OSError):
            pass

    for cand in ("/catkin_ws/src/livox_camera_calib",
                 os.path.expanduser("~/catkin_ws/src/livox_camera_calib"),
                 "/root/catkin_ws/src/livox_camera_calib"):
        if os.path.isdir(os.path.join(cand, "config")):
            return cand
    return None


# Keys CALIB_TEMPLATE emits, as livox_camera_calib reads them ("section/key").
EMITTED_KEYS = [
    "common/image_file", "common/pcd_file", "common/result_file",
    "camera/camera_matrix", "camera/dist_coeffs",
    "calib/calib_config_file", "calib/use_rough_calib",
]


def verify_param_names(repo):
    """Check the keys we emit actually appear in the calibrator's source.

    The ROS1 single-image config layout was inferred from multi_calib.yaml; this turns
    that inference into a checked fact wherever the source is available.
    """
    srcs = []
    for sub in ("src", "include"):
        d = os.path.join(repo, sub)
        if not os.path.isdir(d):
            continue
        for root, _, files in os.walk(d):
            for fn in files:
                if fn.endswith((".cpp", ".hpp", ".h", ".cc")):
                    srcs.append(os.path.join(root, fn))
    if not srcs:
        return None

    blob = ""
    for f in srcs:
        try:
            with open(f, errors="ignore") as fh:
                blob += fh.read()
        except OSError:
            pass

    found = set(re.findall(r'"([a-zA-Z_]+/[a-zA-Z_]+)"', blob))
    missing = [k for k in EMITTED_KEYS if k not in found]
    return found, missing


def parse_intrinsics(path):
    """Read views/intrinsics.txt written by calib_prepare_views.py cut."""
    vals, views = {}, []
    with open(path) as f:
        for line in f:
            line = line.split('#')[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) == 2 and not parts[0].endswith('.png'):
                try:
                    vals[parts[0]] = float(parts[1])
                except ValueError:
                    pass
            elif len(parts) == 3 and parts[0].endswith('.png'):
                views.append((parts[0], float(parts[1]), float(parts[2])))
    missing = {'fx', 'fy', 'cx', 'cy'} - set(vals)
    if missing:
        raise SystemExit(f"{path}: missing {sorted(missing)}")
    if not views:
        raise SystemExit(f"{path}: no view entries found")
    return vals, views


def load_guess(path):
    """Read a 4x4 initial extrinsic (OpenCV convention) as 16 floats."""
    nums = []
    with open(path) as f:
        for line in f:
            line = line.split('#')[0].strip()
            if line:
                nums.extend(float(v) for v in line.replace(',', ' ').split())
    if len(nums) != 16:
        raise SystemExit(f"{path}: expected 16 numbers, got {len(nums)}")
    return nums


def write_opencv_config(base_text, extrinsic, out_path):
    """Copy the scene config, swapping in this view's ExtrinsicMat.

    Edited as text rather than parsed and re-emitted: the file is read by
    cv::FileStorage, which needs the exact '%YAML:1.0' header and '!!opencv-matrix'
    tag that a generic YAML round-trip would strip.
    """
    rows = [", ".join(f"{v:.9f}" for v in extrinsic[i * 4:(i + 1) * 4]) for i in range(4)]
    block = ("data: [" + rows[0] + ",\n         " + rows[1]
             + ",\n         " + rows[2] + ",\n         " + rows[3] + "]")
    new_text, n = re.subn(r"data:\s*\[[^\]]*\]", block, base_text, count=1)
    if n != 1:
        raise SystemExit("could not locate the ExtrinsicMat 'data: [...]' block in the "
                         "scene config -- has its format changed?")
    with open(out_path, "w") as f:
        f.write(new_text)


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--calib-data", default=os.path.join(HERE, "data"),
                   help="bundle data dir holding views/, guesses/ and cloud.pcd")
    p.add_argument("--calib-repo",
                   help="cloned livox_camera_calib repo; its config_<scene>.yaml is used "
                        "as the tuning base. Omitted => built-in defaults.")
    p.add_argument("--out", default=os.path.join(HERE, "configs"))
    p.add_argument("--scene", choices=["outdoor", "indoor"], default="outdoor")
    p.add_argument("--pkg", default="livox_camera_calib", help="ROS1 package name")
    p.add_argument("--exe", default="lidar_camera_calib", help="node executable name")
    p.add_argument("--no-rough", action="store_true",
                   help="set use_rough_calib false (try if the rough search wanders)")
    args = p.parse_args()

    data = os.path.abspath(os.path.expanduser(args.calib_data))
    out = os.path.abspath(os.path.expanduser(args.out))
    views_dir = os.path.join(data, "views")
    guess_dir = os.path.join(data, "guesses")
    pcd = os.path.join(data, "cloud.pcd")

    for path, what in [(views_dir, "views dir"), (guess_dir, "guesses dir"),
                       (pcd, "cloud.pcd")]:
        if not os.path.exists(path):
            raise SystemExit(f"missing {what}: {path}\n"
                             f"Did the bundle's data/ directory get copied across?")

    repo = find_calib_repo(args.calib_repo)
    if repo:
        base_cfg = os.path.join(repo, "config", f"config_{args.scene}.yaml")
        if not os.path.exists(base_cfg):
            raise SystemExit(f"found repo at {repo} but no config/config_{args.scene}.yaml")
        with open(base_cfg) as f:
            base_text = f.read()
        base_desc = base_cfg
    else:
        base_text = FALLBACK_SCENE_CFG
        base_desc = ("built-in defaults -- livox_camera_calib not found; "
                     "pass --calib-repo to match your clone's tuning")

    intr, views = parse_intrinsics(os.path.join(views_dir, "intrinsics.txt"))
    guesses = sorted(f for f in os.listdir(guess_dir) if f.startswith("guess_"))
    if len(guesses) != len(views):
        raise SystemExit(f"{len(views)} views but {len(guesses)} guess files -- "
                         f"regenerate both with the same --views count")

    results_dir = os.path.join(out, "results")
    os.makedirs(results_dir, exist_ok=True)

    print(f"intrinsics : fx={intr['fx']:.4f} fy={intr['fy']:.4f} "
          f"cx={intr['cx']:.1f} cy={intr['cy']:.1f}  (distortion zero)")
    print(f"cloud      : {pcd}")
    print(f"tuning base: {base_desc}")

    if repo:
        checked = verify_param_names(repo)
        if checked is None:
            print("param names: source not readable, skipping check")
        else:
            found, missing = checked
            if missing:
                print("\n  !! PARAM NAME MISMATCH -- the calibrator does not appear to read:")
                for k in missing:
                    print(f"       {k}")
                sectioned = sorted(k for k in found if k.split('/')[0] in
                                   ("common", "camera", "calib"))
                if sectioned:
                    print("     It does read these section keys:")
                    for k in sectioned:
                        print(f"       {k}")
                print("     Your build likely uses a different config layout; the generated\n"
                      "     files would load as defaults (all zeros). Send me the list above.")
            else:
                print(f"param names: verified against {os.path.basename(repo)} source "
                      f"({len(EMITTED_KEYS)}/{len(EMITTED_KEYS)} keys match)")
    print()

    launch_path = os.path.join(out, "calib_view.launch")
    with open(launch_path, "w") as f:
        f.write(LAUNCH_TEMPLATE.format(pkg=args.pkg, exe=args.exe,
                                       launch_path=launch_path))

    compose = []
    for idx, ((view_file, yaw, _pitch), guess_file) in enumerate(zip(views, guesses)):
        scene_out = os.path.join(out, f"config_{idx:02d}.yaml")
        calib_out = os.path.join(out, f"calib_{idx:02d}.yaml")
        result_out = os.path.join(results_dir, f"extrinsic_{idx:02d}.txt")

        write_opencv_config(base_text,
                            load_guess(os.path.join(guess_dir, guess_file)), scene_out)
        with open(calib_out, "w") as f:
            f.write(CALIB_TEMPLATE.format(
                idx=idx, yaw=yaw,
                image_file=os.path.join(views_dir, view_file),
                pcd_file=pcd, result_file=result_out,
                fx=intr['fx'], fy=intr['fy'], cx=intr['cx'], cy=intr['cy'],
                scene_cfg=scene_out,
                rough="false" if args.no_rough else "true"))

        print(f"  view {idx:02d} yaw={yaw:+7.2f}  calib_{idx:02d}.yaml + "
              f"config_{idx:02d}.yaml  (guess: {guess_file})")
        compose.append((yaw, result_out))

    run_all = os.path.join(out, "run_all.sh")
    with open(run_all, "w") as f:
        f.write("#!/bin/bash\n"
                "# Auto-generated. Runs livox_camera_calib once per virtual view.\n"
                "# Each view has its own initial extrinsic, so they cannot share a run.\n"
                "set -e\n"
                f'LAUNCH="{launch_path}"\n\n')
        for idx in range(len(views)):
            f.write(f'echo "=== view {idx:02d} ==="\n'
                    f'roslaunch "$LAUNCH" config:={out}/calib_{idx:02d}.yaml\n\n')
        f.write('echo "All views done. Results in:"\n'
                f'echo "  {results_dir}"\n')
    os.chmod(run_all, os.stat(run_all).st_mode | stat.S_IXUSR | stat.S_IXGRP)

    print(f"\nWrote {len(views)} config pairs, calib_view.launch and run_all.sh to:\n  {out}")
    print("\nThe cloned repo is not modified: calib_view.launch takes the config as an\n"
          "argument, unlike the repo's own calib.launch which hardcodes config/calib.yaml.")
    print(f"\nRun everything:\n  bash {run_all}")
    print("\nOr one view at a time:")
    print(f"  roslaunch {launch_path} config:={out}/calib_00.yaml")

    print("\nThen, back on the ROS2 side:\n")
    print("  python3 calib/calib_prepare_views.py compose \\")
    for yaw, res in compose:
        print(f"      --view-yaw {yaw:g} --extrinsic {res} \\")
    print("      --out calib/data/T_cam_lidar.txt")


if __name__ == "__main__":
    main()
